export const CANADA_CITIES = [
  "Calgary",
  "Edmonton",
  "Vancouver",
  "Burnaby",
  "Surrey",
  "Richmond",
  "Toronto",
  "Mississauga",
  "Brampton",
  "Markham",
  "Vaughan",
  "Ottawa",
  "Hamilton",
  "Kitchener",
  "Waterloo",
  "Guelph",
  "London",
  "Windsor",
  "Montreal",
  "Laval",
  "Longueuil",
  "Brossard",
  "Quebec City",
  "Sherbrooke",
  "Gatineau",
  "Trois-Rivières",
  "Halifax",
  "Dartmouth",
  "Bedford",
  "Sydney",
  "Moncton",
  "Fredericton",
  "Saint John",
  "Charlottetown",
  "St. John's",
  "Corner Brook",
  "Mount Pearl",
  "Whitehorse",
  "Yellowknife",
  "Iqaluit",
];
